{{- $component := "subscriber" -}}
{{- if (index .Values $component).enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rawdata.secret.name" . | quote }}
  labels:
    {{- include "rawdata.labels" . | nindent 4 }}
data:
  appsettings.json:
    ew0KICAgICJBenVyZUFEIjogIHsNCiAgICAgICAgICAgICAgICAgICAgIkluc3RhbmNlIjogICJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vIiwNCiAgICAgICAgICAgICAgICAgICAgIkRvbWFpbiI6ICAiZ3J1bmRmb3Mub25taWNyb3NvZnQuY29tIiwNCiAgICAgICAgICAgICAgICAgICAgIkNsaWVudElkIjogICI3ODk4MjhlOS1kZTU4LTQ2ZGYtOGQwMi1hNmM5OGJjNGNjZTUiLA0KICAgICAgICAgICAgICAgICAgICAiQ2xpZW50U2VjcmV0IjogICI4WXhIVHB5VUp6bFlrK3pZb3Q1Y1BPV0Q2Z2JSV0lkUjhiNW55RkVuU1RzPSIsDQogICAgICAgICAgICAgICAgICAgICJBdWRpZW5jZSI6ICAiaHR0cHM6Ly93d25jLXJhdy1kYXRhLXEtYXp3ZSIsDQogICAgICAgICAgICAgICAgICAgICJUZW5hbnRJZCI6ICAiZGFiZDVkOTAtODdjMi00NGM5LTkzY2QtNzgzZTAzMjM2ZTQwIiwNCiAgICAgICAgICAgICAgICAgICAgIktleVZhdWx0VXJpIjogICJodHRwczovL2dmLWtleXYtd3duYy1yYXctZGEtcS0xLnZhdWx0LmF6dXJlLm5ldC8iDQogICAgICAgICAgICAgICAgfQ0KfQ0K
type: Opaque
{{- end }}
