{{- $component := "runner" -}}
{{- if (index .Values $component).enabled -}}
apiVersion: v1
data:
  appsettings.json: |
    {
        "Serilog": {
            "MinimumLevel": "Debug"
        }
    }
kind: ConfigMap
metadata:
  name: {{ include "rawdata.runner.cm.name" . | quote }}
  labels:
    {{- include "rawdata.labels" . | nindent 4 }}
{{- end }}
