{{- $component := "api" -}}
{{- if (index .Values $component).enabled -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "rawdata.api.name" . | quote }}
  labels:
    {{- include "rawdata.labels" . | nindent 4 }}
spec:
  minReplicas: 1
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "rawdata.api.name" . | quote }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory 
        target:
          type: Utilization
          averageUtilization: 75
{{- end }}